config/routes.rb
Todos::Application.routes.draw do
 
  root to: 'high_voltage/pages#show', id: 'homepage'
  resources :todos, only: [:index, :new, :create] do
  	resource :completion, only: [:create]
  end
  resource :session, only: [:new, :create, :destroy]
end

app/models/guest.rb
class Guest

	def signed_in?
		false
	end
	
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :description

  def user=(new_user)
  	self.owner_email = new_user.email
  end
  
end

app/models/user.rb
class User

	attr_reader :email

	def initialize(email)
		@email = email
	end

	def signed_in?
		true
	end
	
	def todos
		Todo.where(owner_email: @email)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_email=(email_address)
  	session[:current_email] = email_address
  end

  def current_email
  	session[:current_email]
  end

  helper_method :current_email

  def current_user
    if current_email
      User.new(current_email)
    else
      Guest.new
    end
  end

	def authenticate
		if !current_user.signed_in?
			redirect_to new_session_path
		end
	end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController

	def create
		todo = Todo.find(params[:todo_id])
		todo.touch :completed_at
		redirect_to todos_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		self.current_email = params[:session][:email]
		redirect_to todos_path
	end

	def destroy
		self.current_email = nil
		redirect_to root_path
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	before_filter :authenticate

	def index
		@todos = current_user.todos
	end

	def new
		@todo = Todo.new
	end

	def create
		todo = Todo.new(params[:todo])
		todo.user = current_user
		todo.save
		redirect_to todos_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def todo_state(todo)
		if todo.completed_at
			'complete'
		else
			''
		end
	end
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<p data-current-user='<%= current_email %>'>
		<%= current_email %>
	</p>

	<%= link_to "Sign out", session_path, method: :delete %>

<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<h1>Todos</h1>
<p data-role='description'>This is an app to create todos!</p>

app/views/todos/index.html.erb
<%= link_to 'Create a Todo', new_todo_path %>

<ul id = 'my-todos'>
	<% @todos.each do |todo| %>
		<li class='<%= todo_state todo %>' id='<%= dom_id todo %>'>
			<%= todo.description %>
			<%= link_to 'Complete', todo_completion_path(todo), method: :post %>
		</li>
	<% end %>
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
	<%= form.label :description %>
	<%= form.text_area :description %>
	<%= form.submit 'Create' %>
<% end %>